{
    "name": "Deducciones",
    "version": "18.0.1.0.0",
    "author": "Ing. Brenda Chacon, Ing. Karen Burgos, Ing. Francisco Flores",
    "website": "https://contaspro.net",
    "images": ['static/description/banner.png',
               'static/description/icon.png',
               'static/description/thumbnail.png'],
    "price": 40,
    "currency": "USD",
    "license": "LGPL-3",
    "category": "Human Resources - Deducciones",
    "depends": [
        "hr", "hr_payroll", "hr_contract", 'hr_attendance'
    ],
    "data": [
        "views/hr_attendance_inherit.xml",
        "data/hr.retencion.isss.csv",
        "data/hr.retencion.afp.csv",
        "data/hr.retencion.renta.csv",
        "data/hr.retencion.tramo.csv",
        "data/res.configuration.csv",

        "data/estructura_salarial_incoe.xml",

        "data/deduccion_ISSS_data.xml",
        "data/deduccion_AFP_data.xml",
        "data/deduccion_ISR_data.xml",
        "data/deduccion_FSV_data.xml",
        "data/deduccion_fondo_pensiones_data.xml",
        "data/deduccion_venta_empleados.xml",
        "data/deduccion_prestamos.xml",
        "data/deduccion_otras.xml",
        "data/hr_contract_type_data.xml",
        "data/deduccion_banco.xml",
        "data/salary_rules_attendance.xml",
        "data/hr_leave_type_data.xml",
        "data/legacy_salary_rules.xml",
        "data/renta_servicios_profesionales.xml",
        "security/hr_retencion_groups.xml",
        "security/ir.model.access.csv",
        "views/hr_payslip_inherit_view.xml",
        "views/hr_payslip_form_inherit.xml",
        "views/hr_leave_vacation_type.xml",
        "views/hr_contract_form_view.xml",
        "views/hr_payroll_structure_form_inherit_view.xml",
        "views/hr_salary_attachment_mass_state_views.xml",
        "views/hr_deductions_download.xml",
        "views/hr_salary_attachment_views_search.xml",
        "views/hr_leave_excel_template.xml",
        # "data/cleanup_deducciones.xml",
    ],
    "installable": True,
    "auto_install": False,
    "summary": "Deducciones de Renta, ISSS y AFP para planilla",
    "description": "Gestiona deducciones automáticas de ISR, AFP e ISR según tramos.",
    'post_init_hook': 'ejecutar_hooks_post_init',
}
